### PR TITLE
Allow function creating tasks

### PR DESCRIPTION
**Pull request by erikmueller**
Hi there, I needed some adjustments to you (very helpful) library I thought you'd be interested in (I separated them into 3 commits so you can also just pick what you want).

**The thing I needed:** Instead of only being able to pass an array of tasks you can now pass a function (that receives `ctx` and construct the array

```js
taskz(ctx => [{}, {}, {}]
```

Things I felt fit (but is breaking):
- Changed the order of arguments as it's much ore likely to pass `ctx` (not needing to set level and the spinner as they're used 99% internally, one could even argue to put up a facade that only receives the `ctx`)
- I accidentally overwrote the `text` fn so I thought it may be better to have a separate fn to set the text on the spinner (can also be used for color and other stuff later)

Again thanks for making this!

### CODE REVIEW

**Comment by ghost** [comment]
@erikmueller @rap2hpoutre by allowing function while creating tasks, I don't think we need `tasks` and `task`  two different entities for subtasks provision, right?

**Comment by erikmueller** [comment]
Not sure what you mean exactly. This (although changing some public facing stuff) does not touch the task/tasks API. You‘re just able to provide a function to taskz() instead of an array (for dynamic task/subtask creation). I didn’t want to change even more of the API.

**Comment by rap2hpoutre** [comment]
Hi @erikmueller ! Thank you so much for your contribution 🎉 and sorry for late answer.

Your contribution is super cool, **could you separate it in three PR**? I guess it will be simpler to review (be sure I will answer faster!) About your 3 great suggestion, here is my current opinion:

## 1

> Instead of only being able to pass an array of tasks you can now pass a function (that receives ctx and construct the array

Great! Submit a PR just for this and I will merge it!

## 2

> Changed the order of arguments as it's much ore likely to pass ctx (not needing to set level and the spinner as they're used 99% internally, one could even argue to put up a facade that only receives the ctx)

I like this! Still it's a breaking change so we will have to release a new major version (this package has not that much download, but we still have to consider current users!)

## 3 

> I accidentally overwrote the text fn so I thought it may be better to have a separate fn to set the text on the spinner (can also be used for color and other stuff later)

Not sure about this one. Will this code still work: https://github.com/rap2hpoutre/taskz#change-text-within-a-task-during-execution?

Again, thank you!!

**Comment by erikmueller** [comment]
Superseded by #11 #12 & #13

**Pull request closed without merging**
